### ISSUE TITLE
This is the only linux tool to convert Dahua's dav videos! Thank you!

### ISSUE THREAD

**Issue by woodholly** [cyraxjoe/dav2mp4#1]
I am very grateful to you for this program, but I am a little concerned about those built-in binary files. What is the source of vendor files ?
Is it possible to build Docker image with Zim and dav3mp4 inside to convert dav to mp4 a bit safely, without granting binary code direct access to main system ?

I'v found Dahua SDK for different platforms (Linux too) at dahua website: https://www.dahuasecurity.com/support/downloadCenter/softwares?id=2 and I think you could be interested too. As far as I know Dahua = Amcrest.

**Comment by woodholly** [comment]
BTW ffmpeg fails to convert all dav files, sometimes it fails, but your tool always works :)

**Comment by cyraxjoe** [comment]
Glad that you find this useful.

About your question, the binary comes directly from an official dahua api (same download center that you mentioned), this is the one that the web player and native applications are using, that's way it always works. 

For some reason the "General PlaySDK" is no longer shown in the download center (at least not for me), only the NetSDK, but apparently if you search for with the right keywords you can still download it: [General_PlaySDK](https://www.dahuasecurity.com/support/downloadCenter/download-search?keyword=General_PlaySDK) the binary comes in that zip/tar along with the manual, this program wraps the native c library. 

> Is it possible to build Docker image with Zim and dav3mp4 inside to convert dav to mp4 a bit safely, without granting binary code direct access to main system?

Of course, I used nix because it integrates well with a project on which I'm using `dav2mp4`, but you can download the sdk on your own, extract it and place the binary in the same location (it should be exactly the same, nothing shady from my part).

**Comment by woodholly** [comment]
@cyraxjoe thanks! BTW they updated the binary

**Comment by cyraxjoe** [comment]
I don't think there is much to add here. Maybe a few honorable mentions about the source of the mysterious libraries.
